var images = [
"A601B2.png",
"A601B3.png",
"B601C1.png",
"B601C2.png",
"B601C3.png",
"Biomes.png",
"Cell 1.png",
"Cell 2.png",
"Cell 3.png",
"Cell 4.png",
"Cell 5.png",
"China Mountain 3.png",
"China Mountain 4.png",
"China Mountain 5.png",
"Circle rock 4.png",
"Circle Rocks 1.png",
"Circle Rocks 2.png",
"Circle Rocks 3.png",
"circle.png",
"classic mountain 1.png",
"classic mountain 2.png",
"classic mountain 3.png",
"Cliff 5.png",
"Cliff 6.png",
"Cliff 7.png",
"foothill1.png",
"foothill2.png",
"foothill3.png",
"hard circle.png",
"hillMound_1.png",
"hillMound_2.png",
"hillMound_3.png",
"hillMound_4.png",
"hillMound_5.png",
"hills.png",
"mesa plates.png",
"mesa.png",
"Mezozoic Test 1.png",
"Mezozoic Test 2.png",
"mountain 1.png",
"mountain 2.png",
"mountain 3.png",
"mountain 4.png",
"Mountain 5.png",
"Mountain 6.png",
"Mountain 7.png",
"Mountain 8.png",
"mountainRange_1.png",
"mountainRange_2.png",
"mountainRange_3.png",
"mountainRange_4.png",
"mountainRange_5.png",
"mountainTerraced_1.png",
"mountainTerraced_2.png",
"mountainTerraced_3.png",
"mountainTerraced_4.png",
"mountainTerraced_5.png",
"noiseHigh.png",
"noiseLow.png",
"Plains 1.png",
"plains cliff.png",
"plateau 1.png",
"plateau 2.png",
"Plateau 3.png",
"plateau 4.png",
"Plateau.png",
"pointed cliff 1.png",
"river_1.png",
"river_2.png",
"river_3.png",
"Rocks 1.png",
"Rocks 2.png",
"rocky9.png",
"rocky99.png",
"Shape 2.png",
"Shape 3.png",
"Shapes.png",
"sharp cliff.png",
"Spine Ghost.png",
"tallMountain_1.png",
"tallMountain_2.png",
"tallMountain_3.png",
"tallMountain_4.png",
"tallMountain_5.png",
"Talus Spine Mezozoic.png",
"Talus Spine.png",
"Test.png",
"Test2.png",
"volcano.png",
"A601B1.png",
"Cliff 1.png",
"China mountain 1.png",
"China mountain 2.png",
"Cliff1alt.png",
"Cliff 10.png",
"Cliff 2.png",
"Cliff 3.png",
"Cliff 4.png",
"Cliff 8.png",
"Cliff 9.png",
"Cliff.png",
"Dunes 1.png",
"Dunes 2.png",
"Dunes 3.png",
"Dunes 4.png",
"Dunes 5.png",
"Range1.png",
"Range2.png",
"Range3.png",
"Range4.png",
"Range5.png",
"Farm 2.png",
"Farm 1.png",
"Plateau-0.png",
"Plateau 2.png",
"Plateau 3-0.png",
"Plateau 4.png",
"zchasm1.png",
"zchasm.png",
"Desert Rock 4.png",
"Desert Rocks 5.png",
"Desert Rock 1.png",
"Desert Rock 2.png",
"Desert Rock 3.png",
"7.png",
"7v2.png",
"1.png",
"2.png",
"2v2.png",
"3.png",
"4.png",
"4v2.png",
"5.png",
"6.png",
"andrewdune3.png",
"andrewdune1.png",
"andrewdune2.png",
"Materials 1.png",
"Pixel_Mountain.png",
"Me_Mountain_2.png",
"Pixel_1.png",
"Pixel_2.png",
"Me_1.png",
"Me_2.png",
"Me_3.png",
"Me_4.png",
"Me_5.png",
"Me_6.png",
"Me_7.png",
"Fjord3.png",
"Fjord4.png",
"Fjord5.png",
"Fjord6.png",
"Fjord7.png",
"Fjord8.png",
"Fjord9.png",
"Fjord10.png",
"Fjord1.png",
"Fjord2.png",
"Me_Mountain.png",
"Me_Mountain_3.png",
"Me_Mountain_4.png",
];
// The low res images (they should all be the same size)
var src_min = "images/min/";
// The max resolution images (Use the same if there are no higher resolution ones available)
var src_max = "images/max/";
// The local source for the image (used in commands)
var src_local = "file://";